### ISSUE TITLE
Blank table issue

### ISSUE THREAD

**Issue by Igoryok95** [SathwikaGone/ChartsAndTables#12]
Hello, when I'm using this json (https://opendata.ecdc.europa.eu/covid19/casedistribution/json/) the table does not load, only a blank page. With other jsons everything is ok, what am I doing wrong?

Here is the error from the console
![image](https://user-images.githubusercontent.com/27699455/197362799-72c22e38-f1bf-4774-990e-2d85bb8329f3.png)

**Comment by SathwikaGone** [comment]
Can you please share screenshot of how are you using this data (https://opendata.ecdc.europa.eu/covid19/casedistribution/json/ - fetch or axios call)or add your project url to have better idea of the issue you are facing.

**Comment by SathwikaGone** [comment]
> Hello, when I'm using this json (https://opendata.ecdc.europa.eu/covid19/casedistribution/json/) the table does not load, only a blank page. With other jsons everything is ok, what am I doing wrong?
> 
> Here is the error from the console ![image](https://user-images.githubusercontent.com/27699455/197362799-72c22e38-f1bf-4774-990e-2d85bb8329f3.png)

Can you please share screenshot of how are you using this data (https://opendata.ecdc.europa.eu/covid19/casedistribution/json/ - fetch or axios call)or add your project url to have better idea of the issue you are facing.

**Comment by Igoryok95** [comment]
> Can you please share screenshot of how are you using this data (https://opendata.ecdc.europa.eu/covid19/casedistribution/json/ - fetch or axios call)or add your project url to have better idea of the issue you are facing.

For now I have downloaded it on my server and used it instead of mock_data. Although in the future I would like to use url instead of local file

**Comment by Igoryok95** [comment]
https://github.com/Igoryok95/ChartTable

Here is clone of working version with test.json file intead of MOCK_DATA.json. If I try to use that json from link (can't upload on git because of size) table dissapears.

You can download and try that json. Mine called covid.json, but as I said, size >25mb (~28mb).

Also, if you tell me how to use url in this table instead of a local file, I will be very grateful

**Comment by SathwikaGone** [comment]
Okay, that's not how it works. The data I have used has id, firstname, lastname, age and so on.. but the data in the link doesn't have it. So you need to modify the code in-order to access the data that the open data link has.

This is where you need to structure the table: https://github.com/SathwikaGone/ChartsAndTables/blob/main/src/Components/Table/columns.js

And mock data I have used has an **array of objects** but the data you are using is not, so remove the every thing before opening square brackets ( [ ) and everything after closing square brackets ( ] )

Thank you!

**Comment by Igoryok95** [comment]
> Okay, that's not how it works. The data I have used has id, firstname, lastname, age and so on.. but the data in the link doesn't have it. So you need to modify the code in-order to access the data that the open data link has.
> 
> This is where you need to structure the table: https://github.com/SathwikaGone/ChartsAndTables/blob/main/src/Components/Table/columns.js
> 
> And mock data I have used has an **array of objects** but the data you are using is not, so remove the every thing before opening square brackets ( [ ) and everything after closing square brackets ( ] )
> 
> Thank you!

I have been already edited columns.js, check the link above.
Also, I can't edit this .json file, it's a task requirement :)

**Comment by SathwikaGone** [comment]
Article reference to implement axios: https://www.freecodecamp.org/news/how-to-use-axios-with-react/

or

If you cant edit the json then use **MockData.records** at
https://github.com/SathwikaGone/ChartsAndTables/blob/main/src/Components/Table/BasicTable.js#L9

**Comment by Igoryok95** [comment]
> Article reference to implement axios: https://www.freecodecamp.org/news/how-to-use-axios-with-react/
> 
> or
> 
> If you cant edit the json then use **MockData.records** at https://github.com/SathwikaGone/ChartsAndTables/blob/main/src/Components/Table/BasicTable.js#L9

Yes, it worked, thanks.

I have 2 more questions:

1. How to use mathematical functions in columns.js in accessor, for example, I have "deaths" and "continentExp", I need to do ("deaths" / "continentExp") * 1000 and display the resulting result in a table cell

2. Can cells be grouped? Let me explain, let's say I have 340 cells with the country Afghanistan, all the data is the same, except date ("dateRep"), "cases" and "deaths". Is there any way to summarize these data and display the total for the entire year so that one country is not duplicated 340 times? Thank you.
![image](https://user-images.githubusercontent.com/27699455/197386808-b2c88d82-aa6b-425a-aafb-4bef4fda2581.png)
